[book]
title = "Everwind 日本語Wiki"
description = "Everwind（エバーウィンド）の日本語攻略Wiki"
authors = ["everwind-jp"]
language = "ja"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/everwind-jp/everwind-jp.github.io"
no-section-label = false
edit-url-template = "https://github.com/everwind-jp/everwind-jp.github.io/edit/master/{path}"
site-url = "/"
